In [5]:
from open3d import *
import copy

mesh_path = 'Model3D/Pringles/Model.ply'

#mesh_path = 'chef.pcd'
#mesh_path = 'rs1.pcd'

print("Load a ply point cloud, print it, and render it")
pcd = read_point_cloud(mesh_path)
print(pcd)
print(np.asarray(pcd.points))
draw_geometries([pcd])

Load a ply point cloud, print it, and render it
PointCloud with 11017 points.
[[0.1935     0.27149999 0.26550001]
 [0.1934     0.27149999 0.26550001]
 [0.1935     0.27149999 0.26550001]
 ...
 [0.2325     0.48750001 0.32570001]
 [0.2325     0.4905     0.32570001]
 [0.2325     0.49349999 0.3256    ]]
